#!/usr/bin/php
<?php
date_default_timezone_set('Asia/Tokyo');

# require aws sdk
require 'AWSSDKforPHP/vendor/autoload.php';

# include Awstar
include __DIR__ . '/../awstar/awstar_autoload.php';

# autoload classes
include __DIR__ . '/../autoload.php';

