#!/usr/bin/php
<?php
date_default_timezone_set('Asia/Tokyo');

# require aws sdk
require 'AWSSDKforPHP/vendor/autoload.php';

# include Awstar
include __DIR__ . '/../awstar/awstar_autoload.php';

# autoload classes
include __DIR__ . '/../autoload.php';

$awsmybillingCommon = new AwsmybillingCommon();
$awsmybillingRRD = new AwsmybillingRRD();

# 情報を取得するサービス一覧を取得する
$serviceList = $awsmybillingCommon->getServiceList();

# RRDファイルを更新する
foreach($serviceList as $serviceName){
  # CloudWatch請求情報をRRDファイル用のフォーマットで取得
  $billingHistory = AwstarCloudWatch::getBillingHistory('-1 days','now','3600',$serviceName,'Asia/Tokyo','%UnixTimestamp:%Sum');
  
  # RRDファイルを更新する
  $awsmybillingRRD->update($billingHistory,__DIR__ . "/../rrd/{$serviceName}.rrd");
}

/*
# 全サービスの複合グラフを作成する
$awsmybillingRRD->mixGraph($serviceList, __DIR__ . "/../rrd", __DIR__ . "/../web/all.gif", 500, 200, '3600', '-7 days', 'now');
*/

/*
# 各サービス別に単体グラフを作成する
foreach($serviceList as $serviceName){
  $awsmybillingRRD->singleGraph(
    $serviceName,
    __DIR__ . "/../rrd/{$serviceName}.rrd",
    __DIR__ . "/../web/{$serviceName}.gif",
    500,
    200,
    '3600',
    '-1 days',
    'now'
  );
}
*/



